### ISSUE TITLE
Slicer-Flatpak python dependencies download script issue 👀Missing python dependencies

### ISSUE THREAD

**Issue by RafaelPalomar** [RafaelPalomar/Slicer-Flatpak#4]
The Slicer-Flatpak infrastructure has a python script that analyzes the generated `python-*-requirements.txt` files after the Slicer CMake configuration pass. 🐍 The script downloads and computes the SHA256 and puts this information in yaml format that will be inserted in the generated `org.slicer.Slicer.yaml` flatpak manifest. 📝

The script that pulls the python dependencies reports missing dependencies in the specified versions: 

```
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python-dicom-requirements-requirements8mz7545g -r /tmp/slicer-flatpak-F8j2ZY30/Slicer/Release/python-dicom-requirements-requirements.txt --abi=cp39m --only-binary=:all: --require-hashes"
Collecting pydicom==2.3.1
  Using cached pydicom-2.3.1-py3-none-any.whl (2.0 MB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
ERROR: Could not find a version that satisfies the requirement Pillow==9.4.0 (from versions: none)
ERROR: No matching distribution found for Pillow==9.4.0
Failed to download
Please fix the module manually in the generated file
```
```
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python-extension-manager-ssl-requirements-requirementspqme2h4q -r /tmp/slicer-flatpak-F8j2ZY30/Slicer/Release/python-extension-manager-ssl-requirements-requirements.txt --abi=cp39m --only-binary=:all: --require-hashes"
Collecting PyJWT==2.6.0
  Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting wrapt==1.15.0
  Using cached wrapt-1.15.0-py3-none-any.whl (22 kB)
Collecting Deprecated==1.2.13
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
ERROR: Could not find a version that satisfies the requirement cffi==1.15.1 (from versions: none)
ERROR: No matching distribution found for cffi==1.15.1
Failed to download
Please fix the module manually in the generated file
```
```
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python-numpy-requirementsj57puqxx -r /tmp/slicer-flatpak-F8j2ZY30/Slicer/Release/python-numpy-requirements.txt --abi=cp39m --only-binary=:all: --require-hashes"
Collecting nose==1.3.76
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
ERROR: Could not find a version that satisfies the requirement numpy==1.24.2 (from versions: none)
ERROR: No matching distribution found for numpy==1.24.2
Failed to download
Please fix the module manually in the generated file
```
```
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python-scipy-requirementsjvb5uk40 -r /tmp/slicer-flatpak-F8j2ZY30/Slicer/Release/python-scipy-requirements.txt --abi=cp39m --only-binary=:all: --require-hashes"
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: none)
ERROR: No matching distribution found for scipy==1.10.1
Failed to download
Please fix the module manually in the generated file
```

I have looked for the missing packages on [https://pypi.org/search](https://pypi.org/search) and found the following versions:

- Pillow==9.5.0 🛏️
- cffi==1.15.1 🔒
- scipy==1.10.1 📊
- numpy==1.24.2 🧮

To make this issue less disruptive for Slicer-Flatpak development, we will add a warning message about the missing dependencies to the generated manifest. ⚠️ **This is not a permanent solution, but it will allow us to continue with the development of Slicer-Flatpak** ⚠️

**Comment by jcfr** [comment]
@RafaelPalomar  Are you using the tool `req2flatpak`[^1] mentioned in:
* https://github.com/flatpak/flatpak-builder-tools/issues/296#issuecomment-1279834172

> re: Support flatpack

I think the issue is due to the fact the hash specified in `python-*-requirements.txt` target a python version different from the one matching the `org.freedesktop.Sdk` runtime `22.08`

https://github.com/RafaelPalomar/Slicer-Flatpak/blob/c9146cd5954c737a0ea444689e3ae81a6aa72bdd/org.slicer.Slicer.yaml#L4-L5

After looking at the version of python associated with that runtime, we can see it is 3.10[^2]:

```
sources:
- kind: git_tag
  track: '3.10'
[...]
```

Assuming my analysis is valid, to address this, we would need to update `Utilities/Scripts/python_package_updater.py` [^3] so that it can look up packages for newer python versions.




[^1]: https://github.com/johannesjh/req2flatpak
[^2]: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-22.08.12.1/elements/include/python3.yml
[^3]: https://github.com/Slicer/Slicer/blob/main/Utilities/Scripts/python_package_updater.py
